server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/cliente
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

cloud:
  aws:
    stack:
      auto: false
    region:
      static: sa-east-1
      auto: false
    credentials:
      access-key: fakeAccessKeyId
      secret-key: fakeSecretAccessKey
    end-point:
      uri: http://localhost:4566
    queue:
      name: cliente-novo